"""Tambah role kasir ke UserRole enum

Revision ID: 1da24a483a0b
Revises: 82f8a9c5fccb
Create Date: 2026-05-04 16:58:03.727736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da24a483a0b'
down_revision: Union[str, Sequence[str], None] = '82f8a9c5fccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.engine.reflection import Inspector

def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Check columns in operational_expenses
    op_cols = [c['name'] for c in inspector.get_columns('operational_expenses')]
    
    if 'vehicle_id' not in op_cols:
        op.add_column('operational_expenses', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    if 'driver_id' not in op_cols:
        op.add_column('operational_expenses', sa.Column('driver_id', sa.Integer(), nullable=True))
        
    # Check if foreign keys exist before creating them
    fks = inspector.get_foreign_keys('operational_expenses')
    fk_cols = [fk['constrained_columns'] for fk in fks]
    
    if ['vehicle_id'] not in fk_cols:
        op.create_foreign_key(None, 'operational_expenses', 'fleet_vehicles', ['vehicle_id'], ['vehicle_id'])
    if ['driver_id'] not in fk_cols:
        op.create_foreign_key(None, 'operational_expenses', 'hr_drivers', ['driver_id'], ['driver_id'])
        
    if 'driver_name' in op_cols:
        op.drop_column('operational_expenses', 'driver_name')
    if 'plate' in op_cols:
        op.drop_column('operational_expenses', 'plate')
    if 'vehicle_type' in op_cols:
        op.drop_column('operational_expenses', 'vehicle_type')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_expenses', sa.Column('vehicle_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('operational_expenses', sa.Column('plate', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('operational_expenses', sa.Column('driver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operational_expenses', type_='foreignkey')
    op.drop_constraint(None, 'operational_expenses', type_='foreignkey')
    op.drop_column('operational_expenses', 'driver_id')
    op.drop_column('operational_expenses', 'vehicle_id')
    # ### end Alembic commands ###
