"""tambah_memori_geofence

Revision ID: 4e12c61d2be6
Revises: d53f63c0c4c1
Create Date: 2026-05-18 06:45:30.523486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e12c61d2be6'
down_revision: Union[str, Sequence[str], None] = 'd53f63c0c4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_table('fuel_logs')
    op.drop_column('delivery_orders', 'customer_name')
    op.create_foreign_key(None, 'tms_route_plan', 'hr_drivers', ['helper_id'], ['driver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tms_route_plan', type_='foreignkey')
    op.add_column('delivery_orders', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('fuel_logs',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_logged', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('km_awal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('km_akhir', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('liters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_rp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicles.vehicle_id'], name='fuel_logs_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('log_id', name='fuel_logs_pkey')
    )
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
